### ISSUE TITLE
Add port 5999 to docker compose

### ISSUE THREAD

**Issue by peterpeterparker** [junobuild/cli#140]
The admin server is now exposed for the Satellite Docker image as well, we should add the port to docker compose

i.e. 5999

```
services:
  juno-console:
    image: junobuild/console:latest
    ports:
      - 5987:5987
      - 5999:5999
    volumes:
      - juno_console:/juno/.juno
      - ./target/deploy:/juno/target/deploy/

volumes:
  juno_console:
```
